analytics: {}
color:
  brandColors:
    - '#f0262b'
    - '#1e516d'
    - '#fed141'
    - '#844a8d'
    - '#c17003'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.220149
  saturation: 0.5
cta: {}
layout_spectrum: 0.484141
name: 'no'
opengraph: {}
purpose: []
typography_spectrum: 0.5
style: the-composer
